# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SyncDAQ_XASauto.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2011, 1009)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_10 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_10.setLineWidth(1)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_path = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pB_path.setFont(font)
        self.pB_path.setObjectName("pB_path")
        self.horizontalLayout.addWidget(self.pB_path)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("font: 75 12pt \"Sans Serif\";\n"
"color: rgb(255, 0, 0);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.sB_BL = QtWidgets.QSpinBox(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sB_BL.setFont(font)
        self.sB_BL.setMinimum(1)
        self.sB_BL.setMaximum(5)
        self.sB_BL.setProperty("value", 3)
        self.sB_BL.setObjectName("sB_BL")
        self.gridLayout_3.addWidget(self.sB_BL, 0, 1, 1, 1)
        self.checkBox_wLaser = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_wLaser.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 100 12pt \"Sans Serif\";")
        self.checkBox_wLaser.setChecked(True)
        self.checkBox_wLaser.setObjectName("checkBox_wLaser")
        self.gridLayout_3.addWidget(self.checkBox_wLaser, 0, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.frame_8)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sB_RN_end = QtWidgets.QSpinBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sB_RN_end.setFont(font)
        self.sB_RN_end.setMinimum(1)
        self.sB_RN_end.setMaximum(9999999)
        self.sB_RN_end.setProperty("value", 1159914)
        self.sB_RN_end.setObjectName("sB_RN_end")
        self.gridLayout_2.addWidget(self.sB_RN_end, 0, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 5, 1, 1)
        self.sB_RN_start = QtWidgets.QSpinBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sB_RN_start.setFont(font)
        self.sB_RN_start.setMinimum(1)
        self.sB_RN_start.setMaximum(9999999)
        self.sB_RN_start.setProperty("value", 1159913)
        self.sB_RN_start.setObjectName("sB_RN_start")
        self.gridLayout_2.addWidget(self.sB_RN_start, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pdI0_1 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_1.sizePolicy().hasHeightForWidth())
        self.pdI0_1.setSizePolicy(sizePolicy)
        self.pdI0_1.setObjectName("pdI0_1")
        self.gridLayout_6.addWidget(self.pdI0_1, 0, 0, 1, 1)
        self.pdI0_2 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_2.sizePolicy().hasHeightForWidth())
        self.pdI0_2.setSizePolicy(sizePolicy)
        self.pdI0_2.setObjectName("pdI0_2")
        self.gridLayout_6.addWidget(self.pdI0_2, 0, 1, 1, 1)
        self.pdI0_3 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_3.sizePolicy().hasHeightForWidth())
        self.pdI0_3.setSizePolicy(sizePolicy)
        self.pdI0_3.setObjectName("pdI0_3")
        self.gridLayout_6.addWidget(self.pdI0_3, 0, 2, 1, 1)
        self.pdI0_4 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_4.sizePolicy().hasHeightForWidth())
        self.pdI0_4.setSizePolicy(sizePolicy)
        self.pdI0_4.setObjectName("pdI0_4")
        self.gridLayout_6.addWidget(self.pdI0_4, 0, 3, 1, 1)
        self.pdI0_5 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_5.sizePolicy().hasHeightForWidth())
        self.pdI0_5.setSizePolicy(sizePolicy)
        self.pdI0_5.setObjectName("pdI0_5")
        self.gridLayout_6.addWidget(self.pdI0_5, 1, 0, 1, 1)
        self.pdI0_6 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_6.sizePolicy().hasHeightForWidth())
        self.pdI0_6.setSizePolicy(sizePolicy)
        self.pdI0_6.setObjectName("pdI0_6")
        self.gridLayout_6.addWidget(self.pdI0_6, 1, 1, 1, 1)
        self.pdI0_7 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_7.sizePolicy().hasHeightForWidth())
        self.pdI0_7.setSizePolicy(sizePolicy)
        self.pdI0_7.setObjectName("pdI0_7")
        self.gridLayout_6.addWidget(self.pdI0_7, 1, 2, 1, 1)
        self.pdI0_8 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_8.sizePolicy().hasHeightForWidth())
        self.pdI0_8.setSizePolicy(sizePolicy)
        self.pdI0_8.setObjectName("pdI0_8")
        self.gridLayout_6.addWidget(self.pdI0_8, 1, 3, 1, 1)
        self.pdI0_9 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_9.sizePolicy().hasHeightForWidth())
        self.pdI0_9.setSizePolicy(sizePolicy)
        self.pdI0_9.setObjectName("pdI0_9")
        self.gridLayout_6.addWidget(self.pdI0_9, 2, 0, 1, 1)
        self.pdI0_10 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_10.sizePolicy().hasHeightForWidth())
        self.pdI0_10.setSizePolicy(sizePolicy)
        self.pdI0_10.setObjectName("pdI0_10")
        self.gridLayout_6.addWidget(self.pdI0_10, 2, 1, 1, 1)
        self.pdI0_11 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_11.sizePolicy().hasHeightForWidth())
        self.pdI0_11.setSizePolicy(sizePolicy)
        self.pdI0_11.setObjectName("pdI0_11")
        self.gridLayout_6.addWidget(self.pdI0_11, 2, 2, 1, 1)
        self.pdI0_12 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_12.sizePolicy().hasHeightForWidth())
        self.pdI0_12.setSizePolicy(sizePolicy)
        self.pdI0_12.setObjectName("pdI0_12")
        self.gridLayout_6.addWidget(self.pdI0_12, 2, 3, 1, 1)
        self.pdI0_13 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_13.sizePolicy().hasHeightForWidth())
        self.pdI0_13.setSizePolicy(sizePolicy)
        self.pdI0_13.setObjectName("pdI0_13")
        self.gridLayout_6.addWidget(self.pdI0_13, 3, 0, 1, 1)
        self.pdI0_14 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_14.sizePolicy().hasHeightForWidth())
        self.pdI0_14.setSizePolicy(sizePolicy)
        self.pdI0_14.setChecked(True)
        self.pdI0_14.setObjectName("pdI0_14")
        self.gridLayout_6.addWidget(self.pdI0_14, 3, 1, 1, 1)
        self.pdI0_15 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI0_15.sizePolicy().hasHeightForWidth())
        self.pdI0_15.setSizePolicy(sizePolicy)
        self.pdI0_15.setChecked(True)
        self.pdI0_15.setObjectName("pdI0_15")
        self.gridLayout_6.addWidget(self.pdI0_15, 3, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pdI_1 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_1.sizePolicy().hasHeightForWidth())
        self.pdI_1.setSizePolicy(sizePolicy)
        self.pdI_1.setObjectName("pdI_1")
        self.gridLayout_7.addWidget(self.pdI_1, 0, 0, 1, 1)
        self.pdI_2 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_2.sizePolicy().hasHeightForWidth())
        self.pdI_2.setSizePolicy(sizePolicy)
        self.pdI_2.setObjectName("pdI_2")
        self.gridLayout_7.addWidget(self.pdI_2, 0, 1, 1, 1)
        self.pdI_3 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_3.sizePolicy().hasHeightForWidth())
        self.pdI_3.setSizePolicy(sizePolicy)
        self.pdI_3.setObjectName("pdI_3")
        self.gridLayout_7.addWidget(self.pdI_3, 0, 2, 1, 1)
        self.pdI_4 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_4.sizePolicy().hasHeightForWidth())
        self.pdI_4.setSizePolicy(sizePolicy)
        self.pdI_4.setObjectName("pdI_4")
        self.gridLayout_7.addWidget(self.pdI_4, 0, 3, 1, 1)
        self.pdI_5 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_5.sizePolicy().hasHeightForWidth())
        self.pdI_5.setSizePolicy(sizePolicy)
        self.pdI_5.setObjectName("pdI_5")
        self.gridLayout_7.addWidget(self.pdI_5, 1, 0, 1, 1)
        self.pdI_6 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_6.sizePolicy().hasHeightForWidth())
        self.pdI_6.setSizePolicy(sizePolicy)
        self.pdI_6.setObjectName("pdI_6")
        self.gridLayout_7.addWidget(self.pdI_6, 1, 1, 1, 1)
        self.pdI_7 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_7.sizePolicy().hasHeightForWidth())
        self.pdI_7.setSizePolicy(sizePolicy)
        self.pdI_7.setObjectName("pdI_7")
        self.gridLayout_7.addWidget(self.pdI_7, 1, 2, 1, 1)
        self.pdI_8 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_8.sizePolicy().hasHeightForWidth())
        self.pdI_8.setSizePolicy(sizePolicy)
        self.pdI_8.setObjectName("pdI_8")
        self.gridLayout_7.addWidget(self.pdI_8, 1, 3, 1, 1)
        self.pdI_9 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_9.sizePolicy().hasHeightForWidth())
        self.pdI_9.setSizePolicy(sizePolicy)
        self.pdI_9.setObjectName("pdI_9")
        self.gridLayout_7.addWidget(self.pdI_9, 2, 0, 1, 1)
        self.pdI_10 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_10.sizePolicy().hasHeightForWidth())
        self.pdI_10.setSizePolicy(sizePolicy)
        self.pdI_10.setObjectName("pdI_10")
        self.gridLayout_7.addWidget(self.pdI_10, 2, 1, 1, 1)
        self.pdI_11 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_11.sizePolicy().hasHeightForWidth())
        self.pdI_11.setSizePolicy(sizePolicy)
        self.pdI_11.setObjectName("pdI_11")
        self.gridLayout_7.addWidget(self.pdI_11, 2, 2, 1, 1)
        self.pdI_12 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_12.sizePolicy().hasHeightForWidth())
        self.pdI_12.setSizePolicy(sizePolicy)
        self.pdI_12.setObjectName("pdI_12")
        self.gridLayout_7.addWidget(self.pdI_12, 2, 3, 1, 1)
        self.pdI_13 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_13.sizePolicy().hasHeightForWidth())
        self.pdI_13.setSizePolicy(sizePolicy)
        self.pdI_13.setChecked(True)
        self.pdI_13.setObjectName("pdI_13")
        self.gridLayout_7.addWidget(self.pdI_13, 3, 0, 1, 1)
        self.pdI_14 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_14.sizePolicy().hasHeightForWidth())
        self.pdI_14.setSizePolicy(sizePolicy)
        self.pdI_14.setObjectName("pdI_14")
        self.gridLayout_7.addWidget(self.pdI_14, 3, 1, 1, 1)
        self.pdI_15 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdI_15.sizePolicy().hasHeightForWidth())
        self.pdI_15.setSizePolicy(sizePolicy)
        self.pdI_15.setObjectName("pdI_15")
        self.gridLayout_7.addWidget(self.pdI_15, 3, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.frame_12)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.comboBox = QtWidgets.QComboBox(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(350, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.gridLayout_4.addWidget(self.frame_12, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.dsb_I0_ll = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dsb_I0_ll.setDecimals(5)
        self.dsb_I0_ll.setMaximum(1.1)
        self.dsb_I0_ll.setSingleStep(0.01)
        self.dsb_I0_ll.setProperty("value", 1e-05)
        self.dsb_I0_ll.setObjectName("dsb_I0_ll")
        self.gridLayout.addWidget(self.dsb_I0_ll, 1, 1, 1, 1)
        self.dsb_I0_ul = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dsb_I0_ul.setDecimals(4)
        self.dsb_I0_ul.setMaximum(1.1)
        self.dsb_I0_ul.setSingleStep(0.01)
        self.dsb_I0_ul.setProperty("value", 0.9999)
        self.dsb_I0_ul.setObjectName("dsb_I0_ul")
        self.gridLayout.addWidget(self.dsb_I0_ul, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dsb_If_ll = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dsb_If_ll.setDecimals(5)
        self.dsb_If_ll.setMaximum(1.1)
        self.dsb_If_ll.setSingleStep(0.01)
        self.dsb_If_ll.setProperty("value", 1e-05)
        self.dsb_If_ll.setObjectName("dsb_If_ll")
        self.gridLayout.addWidget(self.dsb_If_ll, 2, 1, 1, 1)
        self.dsb_If_ul = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dsb_If_ul.setDecimals(4)
        self.dsb_If_ul.setMaximum(1.1)
        self.dsb_If_ul.setSingleStep(0.01)
        self.dsb_If_ul.setProperty("value", 0.9999)
        self.dsb_If_ul.setObjectName("dsb_If_ul")
        self.gridLayout.addWidget(self.dsb_If_ul, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_9 = QtWidgets.QFrame(self.frame_10)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_15 = QtWidgets.QFrame(self.frame_9)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pB_run = QtWidgets.QPushButton(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pB_run.setFont(font)
        self.pB_run.setObjectName("pB_run")
        self.horizontalLayout_8.addWidget(self.pB_run)
        self.progressBar = QtWidgets.QProgressBar(self.frame_15)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_8.addWidget(self.progressBar)
        self.horizontalLayout_4.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_9)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.frame_16)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame_16)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_9.addWidget(self.lcdNumber_2)
        self.horizontalLayout_4.addWidget(self.frame_16)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(0, 300))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_2.addWidget(self.textBrowser_2)
        self.frame_11 = QtWidgets.QFrame(self.splitter)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(660, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_12 = QtWidgets.QLabel(self.frame_14)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(300, 50))
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_7.addWidget(self.lcdNumber)
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_3 = QtWidgets.QWidget(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(50, 50))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_8.addWidget(self.widget_3, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_17)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(1000, 830))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(self.frame_13)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.frame_13)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.verticalLayout_3.addWidget(self.frame_13)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2011, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pB_path.setText(_translate("MainWindow", "Set Output"))
        self.label_6.setText(_translate("MainWindow", "BL:"))
        self.checkBox_wLaser.setText(_translate("MainWindow", "pump-probe"))
        self.label_8.setText(_translate("MainWindow", "end:"))
        self.label_10.setText(_translate("MainWindow", "Runs"))
        self.label_7.setText(_translate("MainWindow", "start:"))
        self.groupBox.setTitle(_translate("MainWindow", "I0"))
        self.pdI0_1.setText(_translate("MainWindow", "1"))
        self.pdI0_2.setText(_translate("MainWindow", "2"))
        self.pdI0_3.setText(_translate("MainWindow", "3"))
        self.pdI0_4.setText(_translate("MainWindow", "4"))
        self.pdI0_5.setText(_translate("MainWindow", "5"))
        self.pdI0_6.setText(_translate("MainWindow", "6"))
        self.pdI0_7.setText(_translate("MainWindow", "7"))
        self.pdI0_8.setText(_translate("MainWindow", "8"))
        self.pdI0_9.setText(_translate("MainWindow", "9"))
        self.pdI0_10.setText(_translate("MainWindow", "10"))
        self.pdI0_11.setText(_translate("MainWindow", "11"))
        self.pdI0_12.setText(_translate("MainWindow", "12"))
        self.pdI0_13.setText(_translate("MainWindow", "13"))
        self.pdI0_14.setText(_translate("MainWindow", "14"))
        self.pdI0_15.setText(_translate("MainWindow", "15"))
        self.groupBox_2.setTitle(_translate("MainWindow", "If"))
        self.pdI_1.setText(_translate("MainWindow", "1"))
        self.pdI_2.setText(_translate("MainWindow", "2"))
        self.pdI_3.setText(_translate("MainWindow", "3"))
        self.pdI_4.setText(_translate("MainWindow", "4"))
        self.pdI_5.setText(_translate("MainWindow", "5"))
        self.pdI_6.setText(_translate("MainWindow", "6"))
        self.pdI_7.setText(_translate("MainWindow", "7"))
        self.pdI_8.setText(_translate("MainWindow", "8"))
        self.pdI_9.setText(_translate("MainWindow", "9"))
        self.pdI_10.setText(_translate("MainWindow", "10"))
        self.pdI_11.setText(_translate("MainWindow", "11"))
        self.pdI_12.setText(_translate("MainWindow", "12"))
        self.pdI_13.setText(_translate("MainWindow", "13"))
        self.pdI_14.setText(_translate("MainWindow", "14"))
        self.pdI_15.setText(_translate("MainWindow", "15"))
        self.label_4.setText(_translate("MainWindow", "Photodiodes"))
        self.label_11.setText(_translate("MainWindow", "Motor"))
        self.label_3.setText(_translate("MainWindow", "lower limit [V]"))
        self.label_9.setText(_translate("MainWindow", "upper limit [V]"))
        self.label.setText(_translate("MainWindow", "I0"))
        self.label_2.setText(_translate("MainWindow", "If"))
        self.label_5.setText(_translate("MainWindow", "Thresholds"))
        self.pB_run.setText(_translate("MainWindow", "run"))
        self.label_13.setText(_translate("MainWindow", "cycle"))
        self.label_12.setText(_translate("MainWindow", "Run:"))

